name: PlaytimeScoreboard
main: com.bobcat00.playtimescoreboard.PlaytimeScoreboard
version: '${project.version}'
author: Bobcat00
description: Show playtime on the scoreboard
api-version: '1.21'
commands:
  playtimescoreboard:
    description: Reload PlaytimeScoreboard
    aliases: ptsb
    usage: "Usage: /playtimescoreboard reload"
    permission: playtimescoreboard.reload
    permission-message: You do not have permission for this command
permissions:
  playtimescoreboard.reload:
    description: Reload PlaytimeScoreboard
    default: op
